name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies by apt
        run: |
          sudo apt update
          sudo apt install -y automake \
                              pkg-config \
                              libpcre3-dev \
                              zlib1g-dev \
                              liblzma-dev
        if: ${{ startsWith( matrix.os, 'ubuntu' ) }}
      - name: Install dependencies by Homebrew
        run: brew install automake pkg-config pcre xz
        if: ${{ startsWith( matrix.os, 'macos' ) }}
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: ag --help
